name: CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Nix
      uses: cachix/install-nix-action@v10

    - name: Build
      run: nix-shell --run "make -j8"

    - name: Generate Documentation
      run: nix-shell --run "make -j8 doc"

    - uses: actions/upload-artifact@v2
      with:
        name: html-documentation
        path: html/
