name: CI

on:
  push:
    branches: [ master ]
    paths:
      - "**.v"
      - "**.ml"
      - "**.mli"
      - "**.yml"
      - "*.nix"
      - Makefile
  pull_request:
    branches: [ master ]
    paths:
      - "**.v"
      - "**.ml"
      - "**.mli"
      - "**.yml"
      - "*.nix"
      - Makefile
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: true

    - uses: cachix/install-nix-action@v15

    - name: Build
      run: nix develop -c make -j8
