name: CI

on:
  push:
    branches: [ master ]
    paths:
      - "**.v"
      - "**.ml"
      - "**.mli"
      - "**.yml"
      - "*.nix"
      - Makefile
  pull_request:
    branches: [ master ]
    paths:
      - "**.v"
      - "**.ml"
      - "**.mli"
      - "**.yml"
      - "*.nix"
      - Makefile
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run: nix-shell --run "make -j8"
